# Generated by Django 4.2.14 on 2025-06-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='addres',
            new_name='address',
        ),
    ]
